#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
   path: /login
   controller: App\PW\SecurityBundle\Controller\SecurityController::login
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
